"""Preset configurations and sequence templates for NeuroAcoustic Sound Studio."""

PRESETS = {
    "Deep Focus (Alpha-Beta)": {
        "start_beat": 10.0,
        "target_beat": 16.0,
        "carrier_freq": 216.0,
        "duration_sec": 300,
        "harmonic_richness": 0.3,
        "noise_type": "pink",
        "isochronic_mode": False,
    },
    "Sleep Induction (Theta-Delta)": {
        "start_beat": 6.0,
        "target_beat": 2.0,
        "carrier_freq": 136.1,
        "duration_sec": 600,
        "harmonic_richness": 0.2,
        "noise_type": "brown",
        "isochronic_mode": True,
    },
    "Meditation Bridge (Alpha-Theta)": {
        "start_beat": 12.0,
        "target_beat": 5.5,
        "carrier_freq": 174.0,
        "duration_sec": 420,
        "harmonic_richness": 0.4,
        "noise_type": "pink",
        "isochronic_mode": False,
    },
    "Quick Energy Boost (Beta-Gamma)": {
        "start_beat": 15.0,
        "target_beat": 35.0,
        "carrier_freq": 320.0,
        "duration_sec": 180,
        "harmonic_richness": 0.1,
        "noise_type": "white",
        "isochronic_mode": True,
    },
}

SCENARIOS = {
    "Deep Focus & Flow": {
        "category": "Focus & Productivity",
        "description": "Gradually ramps from a calm 10 Hz Alpha state up to 16 Hz High Beta to enhance concentration, linear logic processing, and focus.",
        "start_beat": 10.0,
        "target_beat": 16.0,
        "carrier_freq": 216.0,
        "duration_sec": 900,
        "noise_type": "pink",
        "isochronic_mode": False,
        "harmonic_richness": 0.25,
    },
    "Power Nap Entrainment": {
        "category": "Sleep & Recovery",
        "description": "Rapidly guides brainwave activity down from Beta to 3.5 Hz Delta for restorative short-duration rest.",
        "start_beat": 14.0,
        "target_beat": 3.5,
        "carrier_freq": 136.1,
        "duration_sec": 1200,
        "noise_type": "brown",
        "isochronic_mode": True,
        "harmonic_richness": 0.2,
    },
    "Anxiety Release Riff": {
        "category": "Stress & Relaxation",
        "description": "Stabilizes overactive high Beta down to an ultra-soothing 7.83 Hz Schumann Resonance Theta wave.",
        "start_beat": 20.0,
        "target_beat": 7.83,
        "carrier_freq": 174.0,
        "duration_sec": 600,
        "noise_type": "pink",
        "isochronic_mode": False,
        "harmonic_richness": 0.4,
    },
}

SEQUENCE_TEMPLATES = {
    "3-Stage Focus Journey (30 Min)": [
        {
            "name": "Stage 1: Alpha Arrival",
            "start_beat": 14.0,
            "target_beat": 10.0,
            "carrier_freq": 216.0,
            "duration_sec": 300,
            "noise_type": "pink",
            "isochronic_mode": False,
            "harmonic_richness": 0.2,
        },
        {
            "name": "Stage 2: Beta Flow Hold",
            "start_beat": 10.0,
            "target_beat": 16.0,
            "carrier_freq": 216.0,
            "duration_sec": 1200,
            "noise_type": "pink",
            "isochronic_mode": False,
            "harmonic_richness": 0.3,
        },
        {
            "name": "Stage 3: Cool Down",
            "start_beat": 16.0,
            "target_beat": 8.0,
            "carrier_freq": 216.0,
            "duration_sec": 300,
            "noise_type": "pink",
            "isochronic_mode": False,
            "harmonic_richness": 0.1,
        },
    ],
    "3-Stage Sleep Descent (20 Min)": [
        {
            "name": "Stage 1: Wind Down",
            "start_beat": 12.0,
            "target_beat": 7.5,
            "carrier_freq": 136.1,
            "duration_sec": 300,
            "noise_type": "brown",
            "isochronic_mode": False,
            "harmonic_richness": 0.3,
        },
        {
            "name": "Stage 2: Theta Sink",
            "start_beat": 7.5,
            "target_beat": 4.0,
            "carrier_freq": 136.1,
            "duration_sec": 450,
            "noise_type": "brown",
            "isochronic_mode": True,
            "harmonic_richness": 0.2,
        },
        {
            "name": "Stage 3: Deep Delta Hold",
            "start_beat": 4.0,
            "target_beat": 1.5,
            "carrier_freq": 136.1,
            "duration_sec": 450,
            "noise_type": "brown",
            "isochronic_mode": True,
            "harmonic_richness": 0.1,
        },
    ],
}
